# Day 1

In [1]:
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()

# Print the features and target names
print("Features:", iris.feature_names)
print("Target Names:", iris.target_names)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target Names: ['setosa' 'versicolor' 'virginica']


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\datasets\base.py:239: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  target = np.empty((n_samples,), dtype=np.int)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\datasets\base.py:243: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, 

In [2]:
print(iris)
print(type(iris))
print(iris.keys())

<class 'sklearn.utils.Bunch'>
{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
    

In [3]:
firstRow = iris.data
secondRow = iris.target
thirdRow = iris['target_names']
for line in iris.DESCR.split('\n'):
    print(line)


# Day 2 14 nov, 2023

In [12]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
#from sklearn.tree import plot_tree


In [13]:
# Load the Iris dataset
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\datasets\base.py:239: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  target = np.empty((n_samples,), dtype=np.int)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\datasets\base.py:243: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, 

In [14]:
# Create a Decision Tree model
model = DecisionTreeClassifier()


In [15]:
# Train the model
model.fit(X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\tree\tree.py:149: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [16]:
# Visualize the Decision Tree
plt.figure(figsize=(12, 8))
plot_tree(model, filled=True, feature_names=iris.feature_names, class_names=iris.target_names)
plt.show()


NameError: name 'plot_tree' is not defined

<Figure size 864x576 with 0 Axes>

In [17]:
# Make predictions on the testing set
predictions = model.predict(X_test)


In [18]:
# Evaluate the model's performance
print(classification_report(y_test, predictions))


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ============

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.4 3.7 1.5 0.2]
[4.8 3.4 1.6 0.2]
[4.8 3.  1.4 0.1]
[4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2]
[5.7 4.4 1.5 0.4]
[5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.3]
[5.7 3.8 1.7 0.3]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.7 0.2]
[5.1 3.7 1.5 0.4]
[4.6 3.6 1.  0.2]
[5.1 3.3 1.7 0.5]
[4.8 3.4 1.9 0.2]
[5.  3.  1.6 0.2]
[5.  3.4 1.6 0.4]
[5.2 3.5 1.5 0.2]
[5.2 3.4 1.4 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[5.4 3.4 1.5 0.4]
[5.2 4.1 1.5 0.1]
[5.5 4.2 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.  3.2 1.2 0.2]
[5.5 3.5 1.3 0.2]
[4.9 3.1 1.5 0.1]
[4.4 3.  1.3 0.2]
[5.1 3.4 1.5 0.2]
[5.  3.5 1.3 0.3]
[4.5 2.3 1.3 0.3]
[4.4 3.2 1.3 0.2]
[5.  3.5 1.6 0.6]
[5.1 3.8 1.9 0.4]
[4.8 3.  1.4 0.3]
[5.1 3.8 1.6 0.2]
[4.6 3.2 1.4 0.2]
[5.3 3.7 1.5 0.2]
[5.  3.3 1.4 0.2]
[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[5.5 2.3 4.  1.3]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4

In [ ]:
Absolutely, incorporating projects and questions for self-assessment is an excellent way to reinforce your learning. Below, I've provided project ideas and questions for each day of your 30-day plan:


### Days 4-8: Supervised Learning - Classification
**Project:** Use the famous Iris dataset or another dataset of your choice to train a classification model (e.g., Logistic Regression) to predict a target variable.

**Q & A:**
1. Explain the difference between supervised and unsupervised learning.
2. How do you split a dataset into training and testing sets in scikit-learn?
3. What are precision, recall, and F1-score, and why are they important in classification?

### Days 9-12: Supervised Learning - Regression
**Project:** Choose a dataset with a continuous target variable and use a regression algorithm (e.g., Linear Regression) to make predictions.

**Q & A:**
1. What is the main difference between classification and regression?
2. Explain the concept of overfitting and how to address it.
3. What are some common evaluation metrics for regression models?

### Days 13-17: Unsupervised Learning
**Project:** Apply a clustering algorithm (e.g., K-Means) to a dataset of your choice for grouping similar data points together.

**Q & A:**
1. What is the purpose of unsupervised learning?
2. How does K-Means clustering work?
3. Explain the concept of dimensionality reduction. 

### Days 18-21: Model Deployment and Serialization
**Project:** Save a trained scikit-learn model and load it for making predictions on new data.

**Q & A:**
1. Why might you want to deploy a machine learning model?
2. How do you save and load a scikit-learn model?
3. What is serialization, and why is it important in machine learning?

### Days 22-25: Specialized Topics
**Project:** Implement a Random Forest or Gradient Boosting model on a dataset and compare its performance with a simpler model.

**Q & A:**
1. What are ensemble methods in machine learning?
2. How do Random Forests differ from Gradient Boosting?
3. In what situations might you prefer using an ensemble method?

### Days 26-30: Capstone Project and Review
**Project:** Work on a comprehensive project that involves loading a dataset, performing data preprocessing, choosing an appropriate model, training and evaluating the model, and deploying it.

**Q & A:**
1. Reflect on the key concepts and techniques you've learned during the 30 days.
2. What challenges did you face during your projects, and how did you overcome them?
3. How might you further enhance and expand upon the projects you've completed?

Feel free to adapt these projects and questions based on your interests and the specific topics you want to explore further. Happy learning!

In [2]:
Day 2:
Learn about loading datasets using scikit-learn.
Practice loading a dataset and exploring its features.
Day 3:
Dive into basic operations like data preprocessing and handling missing values.
Explore different preprocessing techniques available in scikit-learn.
Days 4-8: Supervised Learning - Classification
Day 4:
Understand the concepts of supervised learning.
Explore classification algorithms in scikit-learn (e.g., Decision Trees, Logistic Regression).
Day 5:
Work on a small project: use a classification algorithm to predict a target variable in a dataset.
Day 6-8:
Explore different evaluation metrics for classification models.
Practice cross-validation and hyperparameter tuning.
Days 9-12: Supervised Learning - Regression
Day 9:
Learn about regression algorithms in scikit-learn.
Day 10:
Work on a regression project: predict a continuous target variable using a regression algorithm.
Day 11-12:
Explore regression evaluation metrics.
Learn about overfitting and underfitting, and how to handle them.
Days 13-17: Unsupervised Learning
Day 13:
Understand the concept of unsupervised learning.
Day 14:
Explore clustering algorithms in scikit-learn (e.g., K-Means).
Day 15-17:
Work on a clustering project: group similar data points together using a clustering algorithm.
Practice dimensionality reduction techniques (e.g., PCA).
Days 18-21: Model Deployment and Serialization
Day 18:
Learn how to save and load models in scikit-learn.
Day 19-21:
Work on deploying a simple scikit-learn model, for example, using Flask.
Days 22-25: Specialized Topics
Day 22-23:
Explore ensemble methods like Random Forests and Gradient Boosting.
Day 24-25:
Learn about text processing using scikit-learn (e.g., text vectorization).
Days 26-30: Capstone Project and Review
Day 26-29:
Work on a comprehensive project that involves multiple aspects of scikit-learn.
Day 30:
Review key concepts, algorithms, and best practices.
Consider areas where you'd like to deepen your understanding.

SyntaxError: invalid syntax (<ipython-input-2-c76b2855dea0>, line 1)